from database import db
from datetime import datetime


class Alert(db.Model):
    """Security alerts generated by the WAF when suspicious activity is detected."""

    __tablename__ = "alerts"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    level = db.Column(db.String(20), nullable=False)        # info / warning / critical
    message = db.Column(db.Text, nullable=False)
    source_ip = db.Column(db.String(45), nullable=True)
    log_id = db.Column(
        db.Integer,
        db.ForeignKey("request_logs.id", ondelete="SET NULL"),
        nullable=True,
    )
    is_read = db.Column(db.Boolean, default=False, nullable=False)

    # Relationship back to the originating request log
    log = db.relationship("RequestLog", backref="alerts", lazy=True)

    def to_dict(self):
        return {
            "id": self.id,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "level": self.level,
            "message": self.message,
            "source_ip": self.source_ip,
            "log_id": self.log_id,
            "is_read": self.is_read,
        }

    def __repr__(self):
        return f"<Alert {self.id} [{self.level}] {self.message[:40]}>"
